os: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  LibraryVersion: 0.2.0


version: 1.0.{build}


install:
  - git submodule update --init --recursive
  - cinst 7zip -x86
  - cinst 7zip.commandline -x86
  - cinst xamarin-component -version 1.1.0.7
  - ps: |
      $tempDir="$pwd\temp"
      $installerUrl="http://www.monogame.net/releases/v3.4/MonoGameSetup.exe"
      $installerFile="$tempDir\MonoGameSetup.zip"
      $installerExtracted="$tempDir\MonoGameSetup"
      $programFiles = "${env:ProgramFiles(x86)}\"
      
      Write-Host "Downloading MonoGame to $installerFile..."
      If ((Test-Path  $tempDir) -eq 0) {
          New-Item -ItemType Directory $tempDir
      }
      Invoke-WebRequest $installerUrl -OutFile $installerFile
      
      Write-Host "Extracting MonoGame to $installerExtracted..."
      7z x -y $installerFile -o"$installerExtracted"
      Write-Host "Copying the MonoGame content pipeline to $programFiles..."
      Copy-Item "$installerExtracted\`$PROGRAMFILES\MSBuild\MonoGame" "$programFiles\MSBuild" -Recurse


before_build:
  - nuget restore Source\GridDominance.sln


build:
  project: Source\GridDominance.sln
  verbosity: minimal


